version: "3.5"

volumes:
  postgres:

networks:
  default:
    driver: bridge

services:
  database:
    image: postgres:latest
    hostname: database
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: rinha
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "dev"]
      interval: 5s
      timeout: 5s
    ports:
      - "5432:5432"
    expose:
      - "5432"
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "1.5GB"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres:/var/lib/postgresql/data

  api1:
    image: insalubre/rinhabackend:latest
    hostname: api1
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"
    expose:
      - "8080"

  api2:
    image: insalubre/rinhabackend:latest
    hostname: api2
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"
    expose:
      - "8080"

  nginx:
    image: nginx
    hostname: api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.5GB"
